"""add status_effects to characters

Revision ID: b4e1bcdf4bff
Revises: a96d3a6e501d
Create Date: 2026-05-05 16:53:47.298227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e1bcdf4bff'
down_revision: Union[str, Sequence[str], None] = 'a96d3a6e501d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_effects', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        # autogenerate misses CHECK constraints (AGENTS.md "Database" note)
        batch_op.create_check_constraint(
            'ck_characters_status_effects_json',
            'json_valid(status_effects)',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        # Drop the CHECK constraint before the column so SQLite's batch
        # table-recreation doesn't attempt to include the constraint for
        # a column that no longer exists.
        batch_op.drop_constraint('ck_characters_status_effects_json', type_='check')
        batch_op.drop_column('status_effects')

    # ### end Alembic commands ###
