"""phase 1 schema

Revision ID: ca912dd07aa8
Revises: 61e51f450db9
Create Date: 2026-04-30 14:38:14.645972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca912dd07aa8'
down_revision: Union[str, Sequence[str], None] = '61e51f450db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('pwd_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('ruleset', sa.Text(), server_default=sa.text("'bfrpg'"), nullable=False),
    sa.Column('house_rules', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('world_state', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('long_summary', sa.Text(), nullable=True),
    sa.Column('module_id', sa.String(length=36), nullable=True),
    sa.Column('module_state', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('image_style', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('json_valid(house_rules)', name='ck_campaigns_house_rules_json'),
    sa.CheckConstraint('json_valid(module_state)', name='ck_campaigns_module_state_json'),
    sa.CheckConstraint('json_valid(world_state)', name='ck_campaigns_world_state_json'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=True),
    sa.Column('tone', sa.Text(), nullable=True),
    sa.Column('estimated_sessions', sa.Integer(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('image_manifest', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('source_session_id', sa.String(length=36), nullable=True),
    sa.Column('public', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('json_valid(content)', name='ck_modules_content_json'),
    sa.CheckConstraint('json_valid(image_manifest)', name='ck_modules_image_manifest_json'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_members',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('owner','player')", name='ck_campaign_members_role'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'user_id')
    )
    op.create_table('generated_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source_image_id', sa.String(length=36), nullable=True),
    sa.Column('edit_instruction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_image_id'], ['generated_images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_hash')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('json_valid(metadata)', name='ck_locations_metadata_json'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('ended_at', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('current_location_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('json_valid(state)', name='ck_sessions_state_json'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('importance', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('source_session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('json_valid(tags)', name='ck_world_facts_tags_json'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_facts', schema=None) as batch_op:
        batch_op.create_index('idx_world_facts_campaign', ['campaign_id'], unique=False)

    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('race', sa.Text(), nullable=False),
    sa.Column('class_name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('hp_current', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('ac', sa.Integer(), nullable=False),
    sa.Column('str_score', sa.Integer(), nullable=False),
    sa.Column('int_score', sa.Integer(), nullable=False),
    sa.Column('wis_score', sa.Integer(), nullable=False),
    sa.Column('dex_score', sa.Integer(), nullable=False),
    sa.Column('con_score', sa.Integer(), nullable=False),
    sa.Column('cha_score', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('alignment', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'alive'"), nullable=False),
    sa.Column('sheet', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('canonical_image_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('json_valid(sheet)', name='ck_characters_sheet_json'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['canonical_image_id'], ['generated_images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index('idx_characters_campaign', ['campaign_id'], unique=False)

    op.create_table('dice_rolls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('actor_kind', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('individual', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('json_valid(individual)', name='ck_dice_rolls_individual_json'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('monsters', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('initiative', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('round_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('current_turn', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('json_valid(initiative)', name='ck_encounters_initiative_json'),
    sa.CheckConstraint('json_valid(monsters)', name='ck_encounters_monsters_json'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npcs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('alive', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('canonical_image_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('json_valid(stats)', name='ck_npcs_stats_json'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['canonical_image_id'], ['generated_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('sender_kind', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True),
    sa.Column('audience', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_id', sa.String(length=36), nullable=True),
    sa.Column('dice_rolls', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('json_valid(audience)', name='ck_session_messages_audience_json'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_session_time', ['session_id', 'created_at'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('equipped', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('properties', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"), nullable=False),
    sa.CheckConstraint('json_valid(properties)', name='ck_inventory_items_properties_json'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spells_known',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('spell_name', sa.Text(), nullable=False),
    sa.Column('spell_level', sa.Integer(), nullable=False),
    sa.Column('prepared', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spells_known')
    op.drop_table('inventory_items')
    with op.batch_alter_table('session_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_session_time')

    op.drop_table('session_messages')
    op.drop_table('npcs')
    op.drop_table('encounters')
    op.drop_table('dice_rolls')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index('idx_characters_campaign')

    op.drop_table('characters')
    with op.batch_alter_table('world_facts', schema=None) as batch_op:
        batch_op.drop_index('idx_world_facts_campaign')

    op.drop_table('world_facts')
    op.drop_table('sessions')
    op.drop_table('locations')
    op.drop_table('generated_images')
    op.drop_table('campaign_members')
    op.drop_table('modules')
    op.drop_table('campaigns')
    op.drop_table('users')
    # ### end Alembic commands ###
